controller:
  image: "hrcode95/myjenkins"
  tag: "v2"
  installPlugins: false
  JCasC:
    defaultConfig: true
  jenkinsUriPrefix: "/jenkins"
  ingress: # this tells Kubernetes to create an ingress object that gives us access to jenkins
    enabled: true
    # Override for the default paths that map requests to the backend
    #paths: []
    apiVersion: networking.k8s.io/v1
    ingressClassName: nginx
    path: "/jenkins"
  serviceType: ClusterIP

agent:
  podTemplates:
    planetarium: |
      - name: planetarium
        label: jenkins-planetarium
        serviceAccount: jenkins-planetarium
        containers:
        - name: docker
          image: docker:18-dind
          privileged: true