controller:
  installPlugins: # in an ideal situation you would specify the version of the plugin you use
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - docker-workflow
    - github-branch-source
    - docker-plugin
    - pipeline-stage-view
    - timestamper
    - github
    - google-oauth-plugin:latest
    - google-source-plugin:latest
    - google-kubernetes-engine:latest
    - google-storage-plugin:latest

  JCasC:
    defaultConfig: true
  jenkinsUriPrefix: "/jenkins"
  ingress: # this tells Kubernetes to create an ingress object that gives us access to jenkins
    enabled: true
    # Override for the default paths that map requests to the backend
    #paths: []
    apiVersion: networking.k8s.io/v1
    ingressClassName: nginx
    path: "/jenkins"

agent:
#  namespace: production
  podTemplates:
    planetarium: |
      - name: planetarium
        label: jenkins-planetarium
        serviceAccount: jenkins-planetarium
        containers:
        - name: docker
          image: docker:18-dind
          privileged: true