spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
---
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

