apiVersion: v1
kind: ConfigMap  #component
metadata:
  name: postgres-config  #arbitrary name
data:  #content
  postgres-host: postgres-cluster-ip-service #name of the service this config is going to be connected.
  postgres-port: '5432'
  postgres-db: postgres
  postgres-user: postgres







