apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: production
spec:
  type: ExternalName
  externalName: postgres-cluster-ip-service.production.svc.cluster.local
  ports:
    - port: 5432